accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'


urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.HomeView.as_view(), name='home'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('detail/', views.UserDetailView.as_view(), name='detail'),
]

recruitments/urls.py
from django.urls import path


from . import views


app_name = 'recruitments'

urlpatterns = [
    path('create/', views.CreateRecruitment.as_view(), name='create_recruitment'),

    path('list/', views.RecruitmentList.as_view(), name='recruitment_list'),

    path('create-question/', views.CreateQuestion.as_view(), name='create_question'),

    path('question-list/', views.QuestionList.as_view(), name='question_list'),

    path('start-test/', views.StartTest.as_view(), name='start_test'),

    path('answer-question/', views.AnswerQuestion.as_view(), name='answer_question'),

    path('finish-test/', views.FinishTest.as_view(), name='finish_test'),

    path('results/', views.Results.as_view(), name='results'),

    path('result/', views.Result.as_view(), name='result'),

    path('analyse/', views.AnalyseResult.as_view(), name='analyse'),

    path('graph/', views.DisplayGraph.as_view(), name='graph'),

]

ynot/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/', include('accounts.urls')),

    path('recruitments/', include('recruitments.urls')),

    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recruitments/models.py
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.TextField()
    subject = models.CharField(max_length=100)
    choice_1 = models.CharField(max_length=100)
    choice_2 = models.CharField(max_length=100)
    choice_3 = models.CharField(max_length=100)
    choice_4 = models.CharField(max_length=100)
    correct_answer = models.CharField(max_length=100)

    def __str__(self):
        return '{}, {}'.format(self.question_text, self.subject)


class Recruitment(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True, default='')
    experience = models.TextField(max_length=100, null=True)
    qualification = models.TextField(max_length=50, null=True)
    created_on = models.DateField(auto_now_add=True)
    expires_on = models.DateField()
    number_of_questions = models.PositiveIntegerField()
    question = models.ManyToManyField(Question, )
    correct_answer_score = models.IntegerField(default=0)
    incorrect_answer_score = models.IntegerField(default=0)

    @property
    def total_score(self):
        return self.correct_answer_score * self.number_of_questions

    def __str__(self):
        return self.name


class RecruitmentAttempt(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    recruitment = models.ForeignKey(Recruitment, on_delete=models.CASCADE)

    @property
    def correct_count(self):
        return self.recruitmentattemptresponse_set.filter(is_correct=True).exclude(question__subject='eq').count()

    @property
    def incorrect_count(self):
        return self.recruitmentattemptresponse_set.filter(is_correct=False).exclude(question__subject='eq').count()

    @property
    def score(self):
        return ((self.correct_count * self.recruitment.correct_answer_score) -
                (self.incorrect_count * self.recruitment.incorrect_answer_score))

    @property
    def eq_score(self):
        eq_qstns = self.recruitmentattemptresponse_set.filter(question__subject='eq')
        lis = []
        for qstn in eq_qstns:
            try:
                lis.append(int(qstn.response))
            except ValueError:
                lis.append(1)
        return sum(lis)

    @property
    def total_score(self):
        return self.eq_score + self.score

    @property
    def subject_score(self):
        subject_list = self.recruitmentattemptresponse_set.all().values_list('question__subject', flat=True)
        subjects = list(set(subject_list))
        marks = []
        for subject in subjects:
            mark = self.recruitmentattemptresponse_set.filter(question__subject=subject, is_correct=True).count()
            marks.append(mark * self.recruitment.correct_answer_score)
        return subjects, marks

    def __str__(self):
        return '{}, {}'.format(self.user, self.recruitment)


class RecruitmentAttemptResponse(models.Model):
    recruitment_attempt = models.ForeignKey(RecruitmentAttempt, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    response = models.TextField()
    is_correct = models.BooleanField(default=False)

recruitments/views.py
from copy import deepcopy
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic, View
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from .models import Recruitment, Question, RecruitmentAttempt, RecruitmentAttemptResponse


class CreateRecruitment(generic.CreateView, LoginRequiredMixin):
    model = Recruitment
    fields = ('name', 'description', 'number_of_questions', 'correct_answer_score',
              'incorrect_answer_score', 'expires_on', 'question')
    template_name = 'recruitments/create-recruitment.html'
    success_url = reverse_lazy('recruitments:recruitment_list')


class RecruitmentList(generic.ListView, LoginRequiredMixin):
    model = Recruitment
    template_name = 'recruitments/recruitment-list.html'
    context_object_name = 'recruitments'

    def get_context_data(self, **kwargs):
        """ Insert the single object into the context dict. """

        context = super(generic.ListView, self).get_context_data(**kwargs)
        context['rec_attempt'] = [rec.recruitment for rec in
                                  RecruitmentAttempt.objects.filter(user=self.request.user)]
        return context


class CreateQuestion(generic.CreateView, LoginRequiredMixin):
    model = Question
    template_name = 'recruitments/create-question.html'
    fields = '__all__'
    success_url = reverse_lazy('recruitments:question_list')


class QuestionList(generic.ListView, LoginRequiredMixin):
    model = Question
    template_name = 'recruitments/question-list.html'
    context_object_name = 'questions'

    def get_context_data(self, **kwargs):
        """ Insert the single object into the context dict. """

        context = super(generic.ListView, self).get_context_data(**kwargs)
        context['qstn_list'] = Question.objects.filter().exclude(subject='eq')
        return context


class StartTest(generic.View, LoginRequiredMixin):
    def get(self, request):
        recruitment = Recruitment.objects.get(id=request.GET['id'])
        question_list = recruitment.question.all()
        question_ids = [question.id for question in question_list]
        recruitment_attempt = RecruitmentAttempt.objects.create(
            user=request.user,
            date=timezone.now().date(),
            recruitment=recruitment,
        )

        request.session['recruitment'] = recruitment.id
        request.session['recruitment_attempt'] = recruitment_attempt.id
        request.session['question_ids'] = question_ids
        request.session['current_index'] = 0

        return redirect('recruitments:answer_question')


class AnswerQuestion(generic.View, LoginRequiredMixin):
    def get(self, request):
        recruitment = Recruitment.objects.get(id=request.session['recruitment'])
        if request.session['current_index'] >= recruitment.number_of_questions:
            return redirect('recruitments:finish_test')

        question = Question.objects.get(id=request.session['question_ids'][request.session['current_index']])
        return render(request, 'recruitments/answer-question.html', {
            'question': question,
            'current_index': request.session['current_index'],
        })

    def post(self, request):
        question = Question.objects.get(id=request.session['question_ids'][request.session['current_index']])
        recruitment_attempt = RecruitmentAttempt.objects.get(id=request.session['recruitment_attempt'])
        answer = request.POST.get('answer', '')

        RecruitmentAttemptResponse.objects.create(
            recruitment_attempt=recruitment_attempt,
            question=question,
            response=answer,
            is_correct=answer == question.correct_answer,
        )

        request.session['current_index'] += 1
        return redirect('recruitments:answer_question')


class FinishTest(generic.View, LoginRequiredMixin):
    def get(self, request):
        recruitment_attempt = RecruitmentAttempt.objects.get(id=request.session['recruitment_attempt'])

        return render(request, 'recruitments/finish-test.html', {'recruitment_attempt': recruitment_attempt})


class Results(generic.ListView, LoginRequiredMixin):
    context_object_name = 'attempts'
    template_name = 'recruitments/results.html'

    def get_queryset(self):
        return RecruitmentAttempt.objects.filter(recruitment__id=self.request.GET['id'])


class Result(generic.ListView, LoginRequiredMixin):
    context_object_name = 'attempt'
    template_name = 'recruitments/result.html'

    def get_queryset(self):
        return RecruitmentAttempt.objects.get(recruitment__id=self.request.GET['id'],
                                              user=self.request.user)


# class AnalyseResult(View, LoginRequiredMixin):
#
#     def get(self, request):
#         results = RecruitmentAttempt.objects.filter(recruitment__id=self.request.GET['id'])
#         f1 = [data.subject_score[1][0] for data in results]
#         f2 = [data.subject_score[1][1] for data in results]
#         print(f1, f2)
#         marks_array = np.array(list(zip(f1, f2)))
#         kmeans = KMeans(n_clusters=3)
#         # Fitting the input data
#         kmeans = kmeans.fit(marks_array)
#         # Getting the cluster labels
#         labels = kmeans.predict(marks_array)
#         # Centroid values
#         centroid = kmeans.cluster_centers_
#         colors = ["g.", "r.", "c.", "y."]
#         for i in range(len(marks_array)):
#             plt.plot(marks_array[i][0], marks_array[i][1], colors[labels[i]], markersize=10)
#         plt.scatter(centroid[:, 0], centroid[:, 1], marker="*", s=150, linewidths=5, zorder=10)
#         plt.show()
#         return redirect('recruitments:recruitment_list')

class AnalyseResult(View, LoginRequiredMixin):

    def get(self, request):
        results = RecruitmentAttempt.objects.filter(recruitment__id=self.request.GET['id'])
        f2 = [data.score for data in results]
        f1 = [data.eq_score for data in results]
        if len(f2) < 4:
            return render(request, 'recruitments/warning.html')
        marks_array = np.array(list(zip(f2, f1)))
        kmeans = KMeans(n_clusters=3)
        # Fitting the input data
        kmeans = kmeans.fit(marks_array)
        # Getting the cluster labels
        labels = kmeans.predict(marks_array)
        # Centroid values
        centroid = kmeans.cluster_centers_
        print(centroid)

        group_1 = []
        group_2 = []
        group_3 = []

        colors = ["g.", "r.", "c.", "y."]
        for i in range(len(marks_array)):
            # plt.plot(marks_array[i][0], marks_array[i][1], colors[labels[i]], markersize=10)
            if labels[i] == 0:
                group_1.append(results[i])
            elif labels[i] == 1:
                group_2.append(results[i])
            else:
                group_3.append(results[i])
        avg_1 = sum([data.score for data in group_1])/len(group_1)
        avg_2 = sum([data.score for data in group_2]) / len(group_2)
        avg_3 = sum([data.score for data in group_3]) / len(group_3)

        if (avg_1 > avg_2) and (avg_1 > avg_3):
            top = group_1
        elif (avg_2 > avg_1) and (avg_2 > avg_3):
            top = group_2
        else:
            top = group_3

        if (avg_1 < avg_2) and (avg_1 < avg_3):
            below_average = group_1
        elif (avg_2 < avg_1) and (avg_2 < avg_3):
            below_average = group_2
        else:
            below_average = group_3

        if avg_1 < avg_2:
            if avg_2 < avg_3:
                average = group_2
            elif avg_3 < avg_1:
                average = group_1
            else:
                average = group_3
        else:
            if avg_1 < avg_3:
                average = group_1
            elif avg_2 < avg_3:
                average = group_2
            else:
                average = group_3
        data = {
            'top': top,
            'average': average,
            'below_average': below_average
        }
        # plt.scatter(centroid[:, 0], centroid[:, 1], marker="*", s=150, linewidths=5, zorder=10)
        # plt.savefig("media/test.svg")
        return render(request, 'recruitments/analyse.html', data)


class DisplayGraph(View):

    def get(self, request):
        return render(request, 'recruitments/displayResult.html')


class AnalyzeResult(View, LoginRequiredMixin):

    def get(self, request):
        results = RecruitmentAttempt.objects.filter(recruitment__id=self.request.GET['id'])
        f1 = [data.subject_score[1][0] for data in results]
        f2 = [data.subject_score[1][1] for data in results]
        marks_array = np.array(list(zip(f1, f2)))
        plt.scatter(f1, f2, c='black', s=7)

        # Euclidean Distance Caculator
        def dist(a, b, ax=1):
            return np.linalg.norm(a - b, axis=ax)

        k = 3
        # X coordinates of random centroids
        c_x = np.random.randint(0, np.max(marks_array) - 5, size=k)

        # Y coordinates of random centroids
        c_y = np.random.randint(0, np.max(marks_array) - 5, size=k)

        centroid = np.array(list(zip(c_x, c_y)), dtype=np.float32)

        c_old = np.zeros(centroid.shape)
        # Cluster Lables(0, 1, 2)
        clusters = np.zeros(len(marks_array))
        # Error func. - Distance between new centroids and old centroids
        error = dist(centroid, c_old, None)

        # Loop will run till the error becomes zero
        while error != 0:

            # Assigning each value to its closest cluster
            for i in range(len(marks_array)):
                distances = dist(marks_array[i], centroid)
                cluster = np.argmin(distances)
                clusters[i] = cluster
            # Storing the old centroid values

recruitments/templates/recruitments/analyse.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header boxed text-center">
<h1>Top Candidates</h1>
<hr />

<table  class="table table-striped">
    <tr>
        <th class="text-center">Name</th>

        <th class="text-center">score</th>
        <th class="text-center">EQ score</th>
        <th class="text-center">Total score</th>
    </tr>
    {% for attempt in top %}
    <tr>
        <td><a href="{% url 'accounts:detail' %}?id={{ attempt.user.id }}" id="myLink">{{ attempt.user.get_full_name }}</a></td>

        <td>{{ attempt.score }}</td>
        <td>{{ attempt.eq_score }}</td>
        <td>{{ attempt.total_score }}</td>
    </tr>
    {% endfor %}
</table>

<h1>Average Candidates</h1>
<hr />

<table  class="table table-striped">
    <tr>
        <th class="text-center">Name</th>

        <th class="text-center">score</th>
        <th class="text-center">EQ score</th>
        <th class="text-center">Total score</th>
    </tr>
    {% for attempt in average %}
    <tr>
        <td><a href="{% url 'accounts:detail' %}?id={{ attempt.user.id }}" id="myLink">{{ attempt.user.get_full_name }}</a></td>

        <td>{{ attempt.score }}</td>
        <td>{{ attempt.eq_score }}</td>
        <td>{{ attempt.total_score }}</td>
    </tr>
    {% endfor %}
</table>

<h1>Below Average Candidates</h1>
<hr />

<table  class="table table-striped">
    <tr>
        <th class="text-center">Name</th>

        <th class="text-center">score</th>
        <th class="text-center">EQ score</th>
        <th class="text-center">Total score</th>
    </tr>
    {% for attempt in below_average %}
    <tr>
        <td><a href="{% url 'accounts:detail' %}?id={{ attempt.user.id }}" id="myLink">{{ attempt.user.get_full_name }}</a></td>

        <td>{{ attempt.score }}</td>
        <td>{{ attempt.eq_score }}</td>
        <td>{{ attempt.total_score }}</td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}
{% block javascript %}
<script>
    $(()=>{

        $('#back').removeClass('hidden');
        $('#back').attr("href", "/recruitments/list/");

    });

</script>
{% endblock %}

recruitments/templates/recruitments/answer-question.html
{% extends 'base.html' %}

{% block content %}

<div class="row boxed " >

<h1>Question {{ current_index |add:1 }}</h1>
<hr />
<form action="" method="post" class="form-check">
    {% csrf_token %}
    <h3>{{ question.question_text }}</h3>
    <p class="radio" style="margin-left: 60px;">
        <input style="width: 15px; height:20px;" type="radio" name="answer" value="{{ question.choice_1 }}" />{{ question.choice_1 }} <br />
        <input style="width: 15px; height:20px;" type="radio" name="answer" value="{{ question.choice_2 }}" />{{ question.choice_2 }} <br />
        <input style="width: 15px; height:20px;" type="radio" name="answer" value="{{ question.choice_3 }}" />{{ question.choice_3 }} <br />
        <input style="width: 15px; height:20px;" type="radio" name="answer" value="{{ question.choice_4 }}" />{{ question.choice_4 }} <br />
    </p>
    <button type="submit" class=" btn btn-primary" style="margin-left:200px;">Submit</button>
</form>
</div>
{% endblock %}

recruitments/templates/recruitments/create-question.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header text-center">

<h1>Add New Question</h1>
<hr />
<div class="row boxed signup-page" >
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-lg" style="float: right;">Add</button>
</form>
</div>
</div>
{% endblock %}

recruitments/templates/recruitments/create-recruitment.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header text-center">

<h1>Create New Recruitment</h1>
<hr />
<div class="row boxed signup-page" >
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit" class="btn btn-primary btn-block" style="float: right;">Create</button>
</form>
</div>
</div>
{% endblock %}

recruitments/templates/recruitments/displayResult.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header boxed text-center">
<img src="/media/test.svg" alt="Mountain View" width="500" height="350">

</div>
{% endblock %}
{% block javascript %}
<script>
    $(()=>{

        $('#back').removeClass('hidden');
        $('#back').attr("href", "/recruitments/list/");

    });

</script>
{% endblock %}

recruitments/templates/recruitments/finish-test.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header boxed text-center">

<h1>Test Completed</h1>
<hr />
<table style="margin-left:400px">
    <tr>
        <td class="text-left">Your score</td>
        <td>: {{ recruitment_attempt.score }}</td>
    </tr>
    <tr>
        <td class="text-left">Correct answers</td>
        <td>: {{ recruitment_attempt.correct_count }}</td>
    </tr>

    <tr>
        <td class="text-left">Incorrect answers</td>
        <td>: {{ recruitment_attempt.incorrect_count }}</td>
    </tr>
</table>
</div>
{% endblock %}

recruitments/templates/recruitments/question-list.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header text-center">


<div class="row boxed " style="padding: 20px; margin-left: 100px; margin-right: 100px;" >
<h1>All Questions</h1>
<hr />

{% for question in qstn_list %}
    <div class="container" style="padding: 20px; margin-left: 100px; font-size: 20px;">
<p class="text-left"><b>Question : </b>{{ question.question_text }}</p>
    <br>
    <p class="text-left"><b>Subject: </b>{{ question.subject }}</p>
    <br>
    <p class="text-left"><b>Options :</b></p>
    <ul class="text-left" style="padding-left: 25px;">

    <li>{{ question.choice_1 }}</li>
    <li>{{ question.choice_2 }}</li>
    <li>{{ question.choice_3 }}</li>
    <li>{{ question.choice_4 }}</li>
</ul>
    <br>
<p class="text-left"><b>Correct Answer: </b>{{ question.correct_answer }}</p>


        </div>
    <hr />
{% endfor %}
    <hr />
    <span class="login-link"><a href="{% url 'recruitments:create_question' %}">Add New Question</a></span>
</div>
</div>
{% endblock %}

recruitments/templates/recruitments/recruitment-list.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header text-center">
<div class="row boxed " style="padding: 20px; margin-left: 100px; margin-right: 100px;" >
<h1>All Recruitments</h1>
<hr />
    <div style="margin-left:60px; font-size:20px">
        <ul>
{% for recruitment in recruitments %}
            <li>
{% if message %}
                <p> {{ message }} </p>
                {% endif %}
<h1 class="text-left" style="margin-top:60px;">{{ recruitment.name }}</h1>
<div style="margin-left:40px; font-size:20px">
<p class="text-left">{{ recruitment.description }}</p>
<p class="text-left">Last Date: {{ recruitment.expires_on }}</p>
<p class="text-left">
    Correct answer score: {{ recruitment.correct_answer_score }}
    <br />
    Incorrect answer score: {{ recruitment.incorrect_answer_score }}
</p>

    </div>
                </li>
        <br><br>
        {% if user.is_staff %}
            <div style="margin-left:20px;">
            <p class="text-left"><a href="{% url 'recruitments:results' %}?id={{ recruitment.id }}" style="color:#ea8019e6"><b>View Results</b></a></p>
        <p class="text-left"><a href="{% url 'recruitments:analyse' %}?id={{ recruitment.id }}" style="color:#ea8019e6"><b>Analyse Results</b></a></p>
        </div>
            {% else %}
            <div style="margin-left:20px;">
{% if recruitment in rec_attempt %}
        <p class="text-left"><a href="{% url 'recruitments:result' %}?id={{ recruitment.id }}" style="color:#ea8019e6"><b>view result</b></a></p>
{% else %}
        <p class="text-left"><a href="{% url 'recruitments:start_test' %}?id={{ recruitment.id }}" style="color:#ea8019e6"><b>Attempt Test</b></a></p>
{% endif %}
        <hr>
            </div>
{% endif%}
<hr/>
{% empty %}
<h6>No recruitments Added Yet</h6>


{% endfor %}
    </ul>
        </div>
</div>
</div>
{% endblock %}

recruitments/templates/recruitments/result.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header boxed text-center" style="font-size:20px">

<h1>Result</h1>
<hr />
<p>User  : {{ attempt.user.get_full_name }}</p>
<p>Score : {{ attempt.score }}</p>
<p>EQ score : {{ attempt.eq_score }}</p>
<p>Total Score : {{ attempt.total_score }}</p>
</div>
{% endblock %}
{% block javascript %}
<script>
    $(()=>{

        $('#back').removeClass('hidden');
        $('#back').attr("href", "/recruitments/list/");

    });

</script>
{% endblock %}

recruitments/templates/recruitments/results.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header boxed text-center">

<h1>Results</h1>
<hr />

<table  class="table table-striped">
    <tr>
        <th class="text-center">Name</th>

        <th class="text-center">score</th>
        <th class="text-center">EQ score</th>
        <th class="text-center">Total score</th>
    </tr>
    {% for attempt in attempts %}
    <tr>
        <td><a href="{% url 'accounts:detail' %}?id={{ attempt.user.id }}" id="myLink">{{ attempt.user.get_full_name }}</a></td>

        <td>{{ attempt.score }}</td>
        <td>{{ attempt.eq_score }}</td>
        <td>{{ attempt.total_score }}</td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}
{% block javascript %}
<script>
    $(()=>{

        $('#back').removeClass('hidden');
        $('#back').attr("href", "/recruitments/list/");

    });

</script>
{% endblock %}

recruitments/templates/recruitments/warning.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header boxed text-center">
<h3> To Analyse Test Results , Atleast 3 students should attempt the test  </h3>

</div>
{% endblock %}
{% block javascript %}
<script>
    $(()=>{

        $('#back').removeClass('hidden');
        $('#back').attr("href", "/recruitments/list/");

    });

</script>
{% endblock %}