accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'


urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.HomeView.as_view(), name='home'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('detail/', views.UserDetailView.as_view(), name='detail'),
]

recruitments/urls.py
from django.urls import path


from . import views


app_name = 'recruitments'

urlpatterns = [
    path('create/', views.CreateRecruitment.as_view(), name='create_recruitment'),

    path('list/', views.RecruitmentList.as_view(), name='recruitment_list'),

    path('create-question/', views.CreateQuestion.as_view(), name='create_question'),

    path('question-list/', views.QuestionList.as_view(), name='question_list'),

    path('start-test/', views.StartTest.as_view(), name='start_test'),

    path('answer-question/', views.AnswerQuestion.as_view(), name='answer_question'),

    path('finish-test/', views.FinishTest.as_view(), name='finish_test'),

    path('results/', views.Results.as_view(), name='results'),

    path('result/', views.Result.as_view(), name='result'),

    path('analyse/', views.AnalyseResult.as_view(), name='analyse'),

    path('graph/', views.DisplayGraph.as_view(), name='graph'),

]

ynot/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/', include('accounts.urls')),

    path('recruitments/', include('recruitments.urls')),

    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin


class UserManager(BaseUserManager):
    """Create and save a user with the given username, email, and password."""

    def _create_user(self, email, first_name, password=None, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email, first_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, first_name, password, **extra_fields)

    def create_superuser(self, email, first_name, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, first_name, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64, blank=True, default='')
    email = models.EmailField(unique=True, db_index=True)
    phone = models.CharField(max_length=20, default='', blank=True)
    resume = models.FileField(null=True, blank=True, upload_to='resumes/')
    # date_of_birth = models.DateField(blank=True, null=True)
    # profile_picture = models.ImageField(blank=True, null=True, upload_to='accounts/users/profile-pictures')
    # experience = models.TextField(max_length=100, null=True)
    # qualification = models.TextField(max_length=50, null=True)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', ]

    objects = UserManager()

    def __str__(self):
        return str(self.email)

    def get_full_name(self):
        return "{} {}".format(self.first_name.title(), self.last_name)

    def get_short_name(self):
        return str(self.first_name)

accounts/forms.py
from django import forms


class RegisterForm(forms.Form):
    YEAR_CHOICES = [year for year in range(1985, 2019)]

    first_name = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'placeholder': 'First name', 'class': 'form-control', 'required': 'required'}))
    last_name = forms.CharField(max_length=20, required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Last name (optional)', 'class': 'form-control'}))

    # qualification = forms.CharField(max_length=20, widget=forms.TextInput(
    #     attrs={'placeholder': 'Educational Qualification', 'class': 'form-control', 'required': 'required'}))
    #
    # experience = forms.CharField(max_length=100, widget=forms.TextInput(
    #     attrs={'placeholder': 'Professional Experience', 'class': 'form-control', 'required': False}))

    phone = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'placeholder': 'Phone Number ', 'class': 'form-control', 'required': False}))

    resume = forms.FileField()

    # date_of_birth = forms.DateField(widget=forms.SelectDateWidget(years=YEAR_CHOICES))
    # profile_picture = models.ImageField(blank=True, null=True, upload_to='accounts/users/profile-pictures')

    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    password = forms.CharField(max_length=24, min_length=6, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password', 'class': 'form-control'}))
    confirm_password = forms.CharField(max_length=24, min_length=6, widget=forms.PasswordInput(
        attrs={'placeholder': 'Confirm password', 'class': 'form-control'}))

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User
from .forms import RegisterForm


class RegisterView(View):
    def get(self, request):
        return render(request, 'accounts/register.html', {'form': RegisterForm()})

    def post(self, request):
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['password'] != form.cleaned_data['confirm_password']:
                messages.add_message(request, messages.ERROR, 'Passwords do not match. Please check.')
                return render(request, 'accounts/register.html', {'form': form})

            try:
                # first_name = form.cleaned_data['first_name']
                # email = form.cleaned_data['email']
                # password = form.cleaned_data['password']
                del form.cleaned_data['confirm_password']
                # del form.cleaned_data['first_name']
                # del form.cleaned_data['email']
                # del form.cleaned_data['password']
                User.objects.create_user(**form.cleaned_data)
                messages.add_message(request, messages.SUCCESS, 'Account created. Please login to continue')
                return redirect('login')
            except IntegrityError:
                messages.add_message(request, messages.ERROR, 'This email is already registered')
                return render(request, 'accounts/register.html', {'form': form})
        print(form.errors)
        return render(request, 'accounts/register.html', {'form': form})


class HomeView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'accounts/home.html')


class UserDetailView(LoginRequiredMixin, View):

    def get(self, request):

        user = User.objects.get(id=request.GET['id'])
        return render(request, 'accounts/detail.html', {'candidate': user})

    def post(self, request):

        file = request.FILES['resume']
        if file.name.endswith('.pdf') or file.name.endswith('.doc'):
            request.user.resume = file
            request.user.save()
            return render(request, 'accounts/detail.html', {'user': request.user})
        return render(request, 'accounts/detail.html',
                      {'user': request.user, 'message': 'Enter a pdf or doc file'})


class IndexView(LoginRequiredMixin, View):

    def get(self, request):
        return redirect('login')


class LogoutView(LoginRequiredMixin, View):

    def get(self, request):
        return redirect('login')

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header boxed text-center" style="font-size:20px">

<h1>Candidate Details</h1>
    <hr/>
    <h2> {{ candidate.get_full_name }}</h2>
    <div>
        <p><b>Email : </b>{{ candidate.email }}</p>
        <p><b>Phone : </b>{{ candidate.phone }}</p>
        <!--<p><b>Date of Birth : </b>{{ user.date_of_birth }}</p>-->

        <!--<p><b>Educational Qualification : </b>{{ user.qualification }}</p>-->
        <!--<p><b>Proffessional Experience : </b>{{ user.experience }}</p>-->
        <p>

            {% if candidate.resume %}
            <a href='{{candidate.resume.url}}' style="color:#ea8019e6"><b>Download Resume</b></a>
            {% elif not user.is_staff%}
            <div class="col-6" style="padding-left: 350px">
            <form action="" method="post" enctype= "multipart/form-data" class="signup-form">
            {% csrf_token %}
             <input type="file" name="resume" id="id_file" class="" width="50%">
                {% if message %}
                <p>{{ message }}</p>
                 {% endif %}
              <button type="submit" class="btn btn-primary">Upload Resume</button>

            </form>
            </div>
            {% else %}
            <a href='#' style="color:#ea8019e6"><b>NO Resume Uploaded </b></a>
            {% endif %}
        </p>
    </div>
</div>
{% endblock %}
{% block javascript %}
<script>
    $(()=>{

        $('#id_file').removeClass('form-control');

    });

</script>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% block content %}
                                    
<div class="col-md-12" style="margin-top: 50px;">
 
{% if user.is_staff %}
		<div class="market-updates">
			<div class="col-md-3 market-update-gd">
				<a href="{% url 'recruitments:create_recruitment' %}">
				<div class="market-update-block clr-block-1">
					<div class="col-md-7 market-update-left">
						<h3>Add</h3>
						<h4>Recruitments</h4>
											</div>
					<div class="col-md-5 market-update-right">
						<i class="fa fa-file-text-o"> </i>
					</div>
				  <div class="clearfix"> </div>
				</div>
				</a>
			</div>
			<div class="col-md-3 market-update-gd">
				<a href="{% url 'recruitments:create_question' %}">
				<div class="market-update-block clr-block-1">
				 <div class="col-md-7 market-update-left">
					<h3>Add</h3>
					<h4>Question</h4>
				  </div>
					<div class="col-md-5 market-update-right">
						<i class="fa fa-question"> </i>
					</div>
				  <div class="clearfix"> </div>
				</div>
			</a>
			</div>
			<div class="col-md-3 market-update-gd">
				<a href="{% url 'recruitments:recruitment_list' %}"> 
				<div class="market-update-block clr-block-1">
					<div class="col-md-7 market-update-left">
						<h3>List</h3>
						<h4>Recruitments</h4>
					</div>
					<div class="col-md-5 market-update-right">
						<i class="fa fa-list"> </i>
					</div>
				  <div class="clearfix"> </div>
				</div>
			</a>
			</div>
			<div class="col-md-3 market-update-gd">
				<a href="{% url 'recruitments:question_list' %}">
				<div class="market-update-block clr-block-1">
					<div class="col-md-7 market-update-left">
						<h3>List</h3>
						<h4>Question</h4>
					</div>
					<div class="col-md-5 market-update-right">
						<i class="fa fa-list-alt"> </i>
					</div>
				  <div class="clearfix"> </div>
				</div>
			</a>
			</div>
		   <div class="clearfix"> </div>
		</div>

{% else %}
<div class="col-md-3 market-update-gd">
				<a href="{% url 'recruitments:recruitment_list' %}">
				<div class="market-update-block clr-block-1">
					<div class="col-md-7 market-update-left">
						<h3>List</h3>
						<h4>Recruitments</h4>
					</div>
					<div class="col-md-5 market-update-right">
						<i class="fa fa-bar-chart"> </i>
					</div>
				  <div class="clearfix"> </div>
				</div>
			</a>

			</div>
	<div class="col-md-3 market-update-gd">
	<a href="{% url 'accounts:detail' %}?id={{ user.id }}">
				<div class="market-update-block clr-block-1">
					<div class="col-md-7 market-update-left">
						<h3>My</h3>
						<h4>Account</h4>
					</div>
					<div class="col-md-5 market-update-right">
						<i class="fa fa-user"> </i>
					</div>
				  <div class="clearfix"> </div>
				</div>
			</a>
	</div>

{% endif %}
</div>
{% endblock%}

accounts/templates/accounts/register.html
{% extends 'outer.html' %}

{% block content %}

<div class="col-xs-6 col-xs-offset-3">

    <div class="text-center">

<h3></h3>
</div>
      <span class="login-link">Already Have an Account ? <a href="{% url 'login'%}">Sign In</a></span>
<div class="row boxed signup-page" >
<h5>Registration Form</h5>
   <form class="" method="post" id="signup_form" enctype= "multipart/form-data">
      {% csrf_token %}
       <br>
       <!-- <div class="col-xs-6">{{ form.first_name.label_tag }}
           {{ form.first_name}}</div>

       <div class="col-xs-6">{{ form.last_name.label_tag }}
        {{ form.last_name}}</div>

       <div class="col-xs-6">{{ form.qualification.label_tag }}
        {{ form.qualification}}
       </div>

       <div class="col-xs-6">{{ form.experience.label_tag }}
        {{ form.experience }}</div>


       <div class="col-xs-6">{{ form.phone.label_tag }}
           {{ form.phone}}</div>

       <div class="col-xs-6">{{ form.date_of_birth.label_tag }}</div>
           <div class="col-xs-6">{{ form.date_of_birth}}</div>

       <div class="col-xs-12">{{ form.about_me.label_tag }}
           {{ form.about_me}}</div>




       <div class="col-xs-12">{{ form.email.label_tag }}
           {{ form.email }}</form></div>

       <div class="col-xs-6">{{ form.password.label_tag }}
           {{ form.password }}</div>

       <div class="col-xs-6">{{ form.confirm_password.label_tag }}
           {{ form.confirm_password }}</div> -->

        {{form.as_p}}
       
           <button type="submit" class="btn btn-primary btn-block">Register</button>
  </form>

</div>
</div>
{% endblock %}