accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'


urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.HomeView.as_view(), name='home'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('detail/', views.UserDetailView.as_view(), name='detail'),
]

ynot/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/', include('accounts.urls')),

    path('recruitments/', include('recruitments.urls')),

    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ynot</title>

    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,400i,500,600,700" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-light bg-light" style="background-color: #ea8019e6;">
  <a class="navbar-brand" href="{% url 'accounts:home' %}">
    <p class="text-center" style="padding: 20px;"> YNOT</p>
  </a>

  <div id="navigation" class="nav_top pull-right  ">
      <nav>
        
      <div class="dropdown" style="float: left;">

  <div class=" btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <span class="avatar "> </span><label>{{user}}</label><i class="fa fa-chevron-down"></i>

  </div>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
<a href="{% url 'accounts:logout' %}" class="dropdown-item"> Logout </a>
  </div>
  
  </div> 
      </nav>
  </div>
</nav>

<div class="container">
  <div class="col-md-12"><a href="{% url 'accounts:home' %}" style="float: left; margin-right: 20px; margin-top: 0px;"><i class="fa fa-home"> </i> Home</a> <a href="#" id="back" class="pull-right hidden">< Back</a></div>
{% block content %}
{% endblock %}
</div>
</div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://canvasjs.com/assets/script/jquery.canvasjs.min.js"></script>

{% block javascript %}
{% endblock %}
{% include 'script.html'%}

</body>
</html>

templates/outer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ynot</title>

    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,400i,500,600,700" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-light bg-light align-items-center" style="background-color: #ea8019e6;">
  <a class="navbar-brand " href="#">
    <p style="padding: 20px;"> YNOT</p>
  </a>
</nav>
{% block content %}
{% endblock %}

<div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

{% block javascript %}
{% endblock %}
{% include 'script.html'%}

</body>
</html>